### ISSUE TITLE
wxThread using method

### ISSUE THREAD

**Issue by OrkhanGG** [PBfordev/wxOpenCVCameras#1]
I'm asking this question here because it will be more relevant and as far as I see, you are quite experienced with wxWidgets and OpenCV bridge building because you know wxWidgets well.

I know this is a demonstration, not a real project, but I need to ask some questions to make things a little clearer.

What's the point of leaving the set bitmap task to the main thread? This slows things down even more, and while you can already play with the pixels in wxThread, I believe the method you chose makes it more difficult.
Rather than sending that much info to the Thread, you can send the thumbnails/panels (in this case the Bitmap Panel). Let the wxThread do the job, not main thread.
Also why to choose this method while you can perform pixel operations such as resizing on each attached thumbnail. 
For example, you can take the size of thumbnail panels and resize the cv::Mat for each thumbnail. 
But the method you use will prevent the user from having different sized instances of the imported frames. That's just one of the reason to get rid of that method.

**Comment by PBfordev** [comment]
>  What's the point of leaving the set bitmap task to the main thread? This slows things down even more, and while you can already play with the pixels in wxThread, I believe the method you chose makes it more difficult. Rather than sending that much info to the Thread, you can send the thumbnails/panels (in this case the Bitmap Panel). Let the wxThread do the job, not main thread. 

I am not sure I understand. With wxWidgets, the rule of a thumb is that only the GUI thread can use GUI classes. This means one should not use `wxBitmap` in a worker thread either, but I believe the way I do it is safe. I could send the captured bitmaps to `wxPanel`s directly, as it is done in [wxOpenCVTest](https://github.com/PBfordev/wxopencvtest), but this comes with another bunch of possible issues. For example, when the event would not be handled (e.g., because the panel was closed), the bitmaps sent with the event would leak. Additionally, IMO the class coupling would be too tight and it is bad enough already. Moreover, I believe that at least in some scenarios using timer-based batch processing can be more efficient than sending individual events. But this is just an example code, I did consider creating a class that would encapsulate both capturing and displaying images for each camera. In the end, for I decided not to.

> Also why to choose this method while you can perform pixel operations such as resizing on each attached thumbnail. For example, you can take the size of thumbnail panels and resize the cv::Mat for each thumbnail. But the method you use will prevent the user from having different sized instances of the imported frames. That's just one of the reason to get rid of that method.

Once again, I am not sure I understand the question(s) here. The expensive pixel manipulations (resizing, converting from `cv::Mat` to `wxBitmap`) are all done in a worker thread, in order to not block the GUI, the GUI thread just distributes the bitmaps to panels, this should cost nothing, except drawing which must be done in the GUI thread anyway. 

As for bitmap dimensions: This project is a proof of concept, not a code to be used as is and one of the priorities was to keep the code as short as simple as possible, with focus on connecting OpenCV and wxWidgets. The thumbnail size is determined at camera initialization and full-frames are captured at the camera-provided size, customizing this in a real application should be trivial.

By the way, if you want to capture images from multiple physical cameras (i.e., not having multiple different sources of video), you are probably better off using `cv::VideoCapture`'s `waitAny()` & `retrieve()` and thus structure your application differently.

**Comment by OrkhanGG** [comment]
Although your answer almost covers my question, there's still something that I don't understand and I'll be waiting for an answer if you don't mind.

I'm asking this because I'm working on a project that's pretty related to this one. I took this as an example.
And I want to be sure how correct my idea is.
Would not it be much more efficient to have only one thread for each address(`cv::VideoCapture` address/index/port)?
And appending the thumbnails to a vector/array?

Let me show an example from my project(Windows10 OS ver.):
![NNBSS_t1](https://user-images.githubusercontent.com/87902492/157750226-fbb09749-19f2-463a-99aa-774baf771719.png)
As you see, there are 4 devices added. When I add a device, I create a thread for it. And thread nearly does the same job as yours.
But, those threads belong to devices, not thumbnails as there may be a lot of instances such as the `OneCameraPanel` of yours. 
So, I simply append a thumbnail to the vector that's the member of `wxThread`. 

For each thumbnail, I get their size and resize the retrieved frame (`cv::Mat`). This way the thumbnails don't need to have the same `cv::Mat` value and therefore instances of the thumbnails can have different sizes. Will this method be a problem for me in the future?
![NNBSS_t2](https://user-images.githubusercontent.com/87902492/157751348-3f2d8d6b-04fb-401d-8540-042c1834ccd2.png)

**Comment by PBfordev** [comment]
I must be extremely dumb today, as I once again, do not understand your question. Are we even talking about the same code?

My code does have a thread per camera (i.e., `cv::VideoCapture`) and each capture thread can actually have a different size thumbnail, see `CameraSetupData::thumbnailSize`. The thumbnail is stored as `wxBitmap`, as it serves only for display. However, the same thumbnail size is used in the code, as that is what is usually displayed in similar applications, where cameras are displayed in a grid with uniformly sized individual views. 

All camera threads are isolated and do not share anything between them (except the vector for grabbed images). Additionally, captured images are saved in a vector shared between the capture and GUI threads, please read the About section of the GitHub project description and the code itself.

But as I already wrote, if you have many cameras, having a thread per each camera may not be the best idea. Using `cv::VideoCapture::waitAny()` would be not only more efficient (e.g., having one capture thread, one processing thread, and the GUI thread where the threads pass the captured images from one to another) but also provide better synchronized captures.
